@baseUrl = http://localhost:{{$dotenv PORT}}/api
@fileName = 200607_133442.log
@boundary = WebKitFormBoundary1234

# @name login
POST {{baseUrl}}/login

@authToken = {{login.response.body.token}}

###
GET {{baseUrl}}/test-login
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/upload
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----{{boundary}}

------{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{fileName}}"
Content-Type: application/octet-stream

< {{fileName}}
------{{boundary}}--




