@baseUrl = http://localhost:8080/api

# @name login
POST {{baseUrl}}/login

@authToken = {{login.response.body.token}}

###
GET http://localhost:8080/api/test-login
Authorization: Bearer {{authToken}}

###
POST http://localhost:8080/api/upload
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="200530_122515.log"
Content-Type: application/octet-stream

< 200530_122515.log
------WebKitFormBoundary7MA4YWxkTrZu0gW--




